# --- Docker Specific Configuration ---

# 1. Vault: Point to the Docker Service name "vault"
spring.cloud.vault.uri=http://vault:8200
spring.config.import=vault://
# 2. Database: Point to the Docker Service name "postgres"
spring.datasource.url=jdbc:postgresql://postgres:5432/mcp_db?stringtype=unspecified

# 3. Case360: Point to the host machine
case360.url=http://host.docker.internal:8080/sonora/soap/Ws
spring.flyway.repair-on-migrate=true